### ISSUE TITLE
Title and Description are equal

### ISSUE THREAD

**Issue by Paul-Riedel** [vimes1984/video_sitemap#3]
sitemap-video.xml
<loc>http://pauls-kochstube.de/?p=1042</loc>
 video:video
  <video:player_loc allow_embed="yes" autoplay="autoplay=1">http://www.youtube.com/v/EjwrSg64L1A/video:player_loc
  video:thumbnail_lochttp://i.ytimg.com/vi/EjwrSg64L1A/hqdefault.jpg/video:thumbnail_loc
  video:titleEier kochen richtig gemacht/video:title
  video:descriptionEier kochen richtig gemacht/video:description
  video:publication_date2015-04-04T11:20:23+00:00/video:publication_date
 /video:video
 </url>

**Comment by Paul-Riedel** [comment]
I was analysing it. You can't read a description, because the description and the video are in the same field.
I have installed the metatag plug-in, thats why I have a description meta tag.
Now, I can just imagine that if there is any comment before the video or an user defined field, than you can provide a different title and description.
Am I right?

**Comment by vimes1984** [comment]
ok mate I have no way of knowing which meta tags you have or don't have on a post..... 
I'm using the https://codex.wordpress.org/Excerpt field to use as a description if the post doesn't have one it will use the title I can'd grab your description since it will be different on each site but you could manually edit the file replacing the descirption where you see fit...

**Comment by Paul-Riedel** [comment]
perfect. Many thanks

**Comment by vimes1984** [comment]
I'm going to close this for now... If you have any other issues just let me know! 
Chris
